blank_issues_enabled: false
contact_links:
  - name: 📖 Contribution Guidelines
    url: https://github.com/notmyfirstcodeo/rugby-always-wins/blob/main/.github/CONTRIBUTING.md#contributing-to-rugby-always-wins
    about: Please read through before making your contributions.